# Generated by Django 2.2.5 on 2020-08-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200823_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='adress',
            new_name='address',
        ),
    ]
