# Generated by Django 2.2.5 on 2020-08-31 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20200831_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='facilites',
            new_name='facilities',
        ),
    ]
